---
- connection: local
  hosts: 127.0.0.1
  tasks:
  - name: Developer | Install homebrew
    command: ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)" creates=/usr/local/bin/brew

  - name: Developer | Update homebrew
    command: brew update

  - name: Developer | Install curl
    homebrew: name=curl state=present

  - name: Developer | Install rvm
    command: "curl -fsSL https://get.rvm.io"

  - name: Developer | Install packages
    homebrew: name={{ item }} state=present
    with_items:
      - gnu-sed
      - git
      - the_silver_searcher
      - redis
      - elasticsearch
      - lftp

  - name: Developer | Install pip packages
    pip: name=xlsx2csv

  - name: Developer | Install ffmpeg
    homebrew: name=ffmpeg install_options="with-fdk-aac"

  - name: Developer | Link real sed
    file: src=/usr/local/bin/gsed dest=/usr/local/bin/sed state=link
